# Generated by Django 3.2.5 on 2021-07-30 11:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arnaud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='poeple',
        ),
        migrations.CreateModel(
            name='Interested',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(default=datetime.datetime(2021, 7, 30, 11, 0, 35, 927310))),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arnaud.image')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arnaud.person')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='persons',
            field=models.ManyToManyField(through='arnaud.Interested', to='arnaud.Person'),
        ),
    ]
