# Generated by Django 3.2.5 on 2021-07-30 14:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arnaud', '0002_auto_20210730_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interested',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 30, 14, 23, 0, 437973)),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arnaud.image')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arnaud.person')),
            ],
        ),
    ]
